### ISSUE TITLE
Modern browsers compatibility. ( Failed to execute 'createObjectURL' on 'URL' )

### ISSUE THREAD

**Issue by reekol** [jasonmayes/JS-Motion-Detection#3]
Replacing:
```
 video.src = window.URL.createObjectURL(stream)
```
 By
```
 video.srcObject = stream
```
should fix the depreciation of using createObjectURL in this context.
Else: ... Failed to execute 'createObjectURL' on 'URL' ... is triggered.

**Comment by jasonmayes** [comment]
Thanks! Will update.
