### ISSUE TITLE
Is there a way to use this code to generate alerts when motion detected?

### ISSUE THREAD

**Issue by zlelik** [jasonmayes/JS-Motion-Detection#4]
I want to make a program like this

```
if (isMotionDetected(sensitivity)) {
  //doSomething();
}

```
I reviewed the code but could not find how I can make it. Is it possible at all or this code is just converting picture to grayscale and highlight motion?

**Comment by jasonmayes** [comment]
Its technically possible but you would need to write this logic yourself.
You may also be interested in my other repo that does real time person removal - you could change that to be other objects with different machine learning models etc. https://github.com/jasonmayes/Real-Time-Person-Removal
