### ISSUE TITLE
https://codelabs.developers.google.com/codelabs/tensorflowjs-object-detection#0

### ISSUE THREAD

**Issue by luca-ferrari-roma** [jasonmayes/JS-Motion-Detection#5]
Good morning Jason,
I'm not sure that this one is the right place to post my question but I need some support by you.

Regarding this post https://codelabs.developers.google.com/codelabs/tensorflowjs-object-detection#0 is it possible, to integrate the code (JS+HTML) inside Node-Red?

![image](https://user-images.githubusercontent.com/39159409/112279649-70255a80-8c84-11eb-8f98-31bb950a318f.png)

How can I do this?
Do you help me?

Thank you.

**Comment by jasonmayes** [comment]
TensorFlow.js is indeed supported by Node Red - you may want to reach out to Paul Van Eck who was recently on our show and tell from IBM who  helped create Node Red who can guide you further on using their interface. I am curious though given the code already works, what you plan to do with Node Red? If you are trying to deploy to raspberry pi, then my code is designed for front end web environment, but I expect Raspberry Pi will require Node.js version to run correctly.
