### ISSUE TITLE
How do I Handle Events when motion is detected!

### ISSUE THREAD

**Issue by destinybravos** [jasonmayes/JS-Motion-Detection#6]
I want to use this code to develop a test project that will send an alert when motion is detected but I can't seem to understand where the event or function is to come in. 

Another thing is to actually check when the motion is very obvious before triggering the event to avoid triggering the event multiple times when there is no significant movement!

**Comment by jasonmayes** [comment]
Correct you would have to add logic to decide when a threshold of change has occurred that you would then define as a significant motion.
